apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 549716479097.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 549716479097.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 14cd1568
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
